spring.application.name=document
spring.datasource.url: jdbc:mysql://localhost:3306/auth_db
spring.datasource.username: root
spring.datasource.password: test

#spring.servlet.multipart.max-file-size: 50MB
#spring.servlet.multipart.max-request-size: 50MB

#azure.blob.enabled: true
#azure.storage.account-name=stnfidocumentstore
##logging.level.com.azure.identity=DEBUG

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port= 9998